//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISErrorLog
    {
        public int ID { get; set; }
        public string LogText { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string FileName { get; set; }
        public string LineNumber { get; set; }
        public string ColumnNumber { get; set; }
        public string Method { get; set; }
        public string Class { get; set; }
    }
}
