//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISStudentHistory
    {
        public int ID { get; set; }
        public string StudentNo { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string StudentName { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ParantName1 { get; set; }
        public string ParantEmail1 { get; set; }
        public string ParantPassword1 { get; set; }
        public string ParantPhone1 { get; set; }
        public string ParantRelation1 { get; set; }
        public string ParantPhoto1 { get; set; }
        public string ParantName2 { get; set; }
        public string ParantEmail2 { get; set; }
        public string ParantPassword2 { get; set; }
        public string ParantPhone2 { get; set; }
        public string ParantRelation2 { get; set; }
        public string ParantPhoto2 { get; set; }
        public string PickupMessageID { get; set; }
        public Nullable<System.TimeSpan> PickupMessageTime { get; set; }
        public Nullable<System.DateTime> PickupMessageDate { get; set; }
        public string PickupMessageLastUpdatedParent { get; set; }
        public string AttendanceEmailFlag { get; set; }
        public Nullable<System.DateTime> LastAttendanceEmailDate { get; set; }
        public Nullable<System.TimeSpan> LastAttendanceEmailTime { get; set; }
        public Nullable<System.TimeSpan> LastUnpickAlertSentTime { get; set; }
        public Nullable<System.DateTime> UnpickAlertDate { get; set; }
        public Nullable<int> LastUnpickAlertSentTeacherID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Out { get; set; }
        public Nullable<bool> Outbit { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDateTime { get; set; }
        public Nullable<bool> EmailAfterConfirmAttendence { get; set; }
        public Nullable<bool> EmailAfterConfirmPickUp { get; set; }
    }
}
