//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISUserRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ISUserRole()
        {
            this.ISTeachers = new HashSet<ISTeacher>();
        }
    
        public int ID { get; set; }
        public int SchoolID { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> RoleType { get; set; }
        public bool ManageTeacherFlag { get; set; }
        public bool ManageClassFlag { get; set; }
        public bool ManageSupportFlag { get; set; }
        public bool ManageStudentFlag { get; set; }
        public bool ManageViewAccountFlag { get; set; }
        public Nullable<bool> ManageNonTeacherFlag { get; set; }
        public Nullable<bool> ManageHolidayFlag { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDateTime { get; set; }
    
        public virtual ISSchool ISSchool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISTeacher> ISTeachers { get; set; }
    }
}
