//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifaction
    {
        public int ID { get; set; }
        public int RecieverGroupId { get; set; }
        public string Message { get; set; }
        public string Subject { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
