//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewStudentAttendence
    {
        public Nullable<int> ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDateTime { get; set; }
        public int StudentsID { get; set; }
        public string StudentNo { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string StudentName { get; set; }
        public string Photo { get; set; }
        public string ParantName1 { get; set; }
        public string ParantEmail1 { get; set; }
        public string ParantName2 { get; set; }
        public string ParantEmail2 { get; set; }
        public Nullable<bool> StudentActive { get; set; }
        public Nullable<bool> StudentDeleted { get; set; }
    }
}
