//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewStudentPickUp
    {
        public int StudID { get; set; }
        public string StudentNo { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string StudentName { get; set; }
        public string Photo { get; set; }
        public string ParantName1 { get; set; }
        public string ParantEmail1 { get; set; }
        public string ParantName2 { get; set; }
        public string ParantEmail2 { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> PickerID { get; set; }
        public Nullable<System.DateTime> PickTime { get; set; }
        public Nullable<System.DateTime> PickDate { get; set; }
        public string PickStatus { get; set; }
    }
}
