//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewNotAssignPicker
    {
        public int ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Photo { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string PickupCodeCunter { get; set; }
        public Nullable<bool> OneOffPickerFlag { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<System.DateTime> ActiveStatusLastUpdatedDate { get; set; }
        public string ActiveStatusLastUpdatedParent { get; set; }
        public string ActiveStatusLastUpdatedParentEmail { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDateTime { get; set; }
    }
}
